// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

type SlotReservation struct {
	// id строки
	ID int32
	// идентификатор заказа
	OrderID string
	// идентификатор диапазона
	SlotID int32
}
