// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeliveryStatus delivery status
//
// swagger:model DeliveryStatus
type DeliveryStatus struct {

	// Статус доставки
	// Example: Confirmed
	DeliveryStatus string `json:"delivery_status"`

	// Идентификатор заказа
	// Example: Заказ №123
	OrderID string `json:"order_id"`
}

// Validate validates this delivery status
func (m *DeliveryStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delivery status based on context it is used
func (m *DeliveryStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeliveryStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeliveryStatus) UnmarshalBinary(b []byte) error {
	var res DeliveryStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
