// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewSlotReserveParams Создание резерва на доставку по заказу
//
// swagger:model NewSlotReserveParams
type NewSlotReserveParams struct {

	// Идентификатор заказа
	// Example: Заказ №123
	// Required: true
	OrderID string `json:"order_id"`

	// Идентификатор слота
	// Example: Заказ №123
	// Required: true
	// Enum: [1 2 3 4]
	SlotID string `json:"slot_id"`
}

// Validate validates this new slot reserve params
func (m *NewSlotReserveParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSlotID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewSlotReserveParams) validateOrderID(formats strfmt.Registry) error {

	if err := validate.RequiredString("order_id", "body", m.OrderID); err != nil {
		return err
	}

	return nil
}

var newSlotReserveParamsTypeSlotIDPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["1","2","3","4"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		newSlotReserveParamsTypeSlotIDPropEnum = append(newSlotReserveParamsTypeSlotIDPropEnum, v)
	}
}

const (

	// NewSlotReserveParamsSlotIDNr1 captures enum value "1"
	NewSlotReserveParamsSlotIDNr1 string = "1"

	// NewSlotReserveParamsSlotIDNr2 captures enum value "2"
	NewSlotReserveParamsSlotIDNr2 string = "2"

	// NewSlotReserveParamsSlotIDNr3 captures enum value "3"
	NewSlotReserveParamsSlotIDNr3 string = "3"

	// NewSlotReserveParamsSlotIDNr4 captures enum value "4"
	NewSlotReserveParamsSlotIDNr4 string = "4"
)

// prop value enum
func (m *NewSlotReserveParams) validateSlotIDEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, newSlotReserveParamsTypeSlotIDPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *NewSlotReserveParams) validateSlotID(formats strfmt.Registry) error {

	if err := validate.RequiredString("slot_id", "body", m.SlotID); err != nil {
		return err
	}

	// value enum
	if err := m.validateSlotIDEnum("slot_id", "body", m.SlotID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this new slot reserve params based on context it is used
func (m *NewSlotReserveParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewSlotReserveParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewSlotReserveParams) UnmarshalBinary(b []byte) error {
	var res NewSlotReserveParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
