// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewSlotReserveParams Создание резерва на доставку по заказу
//
// swagger:model NewSlotReserveParams
type NewSlotReserveParams struct {

	// Идентификатор заказа
	// Example: Заказ №123
	// Required: true
	OrderID string `json:"order_id"`

	// Идентификатор слота
	// Example: Заказ №123
	// Required: true
	SlotID string `json:"slot_id"`
}

// Validate validates this new slot reserve params
func (m *NewSlotReserveParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSlotID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewSlotReserveParams) validateOrderID(formats strfmt.Registry) error {

	if err := validate.RequiredString("order_id", "body", m.OrderID); err != nil {
		return err
	}

	return nil
}

func (m *NewSlotReserveParams) validateSlotID(formats strfmt.Registry) error {

	if err := validate.RequiredString("slot_id", "body", m.SlotID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this new slot reserve params based on context it is used
func (m *NewSlotReserveParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewSlotReserveParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewSlotReserveParams) UnmarshalBinary(b []byte) error {
	var res NewSlotReserveParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
