// Code generated by go-swagger; DO NOT EDIT.

package delivery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"otusdelivery/internal/models"
)

// DeleteUnreserveSlotOrderIDOKCode is the HTTP code returned for type DeleteUnreserveSlotOrderIDOK
const DeleteUnreserveSlotOrderIDOKCode int = 200

/*
DeleteUnreserveSlotOrderIDOK Успешное получение данных по балансу

swagger:response deleteUnreserveSlotOrderIdOK
*/
type DeleteUnreserveSlotOrderIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewDeleteUnreserveSlotOrderIDOK creates DeleteUnreserveSlotOrderIDOK with default headers values
func NewDeleteUnreserveSlotOrderIDOK() *DeleteUnreserveSlotOrderIDOK {

	return &DeleteUnreserveSlotOrderIDOK{}
}

// WithPayload adds the payload to the delete unreserve slot order Id o k response
func (o *DeleteUnreserveSlotOrderIDOK) WithPayload(payload *models.DefaultStatusResponse) *DeleteUnreserveSlotOrderIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete unreserve slot order Id o k response
func (o *DeleteUnreserveSlotOrderIDOK) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUnreserveSlotOrderIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUnreserveSlotOrderIDInternalServerErrorCode is the HTTP code returned for type DeleteUnreserveSlotOrderIDInternalServerError
const DeleteUnreserveSlotOrderIDInternalServerErrorCode int = 500

/*
DeleteUnreserveSlotOrderIDInternalServerError Серверная ошибка

swagger:response deleteUnreserveSlotOrderIdInternalServerError
*/
type DeleteUnreserveSlotOrderIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewDeleteUnreserveSlotOrderIDInternalServerError creates DeleteUnreserveSlotOrderIDInternalServerError with default headers values
func NewDeleteUnreserveSlotOrderIDInternalServerError() *DeleteUnreserveSlotOrderIDInternalServerError {

	return &DeleteUnreserveSlotOrderIDInternalServerError{}
}

// WithPayload adds the payload to the delete unreserve slot order Id internal server error response
func (o *DeleteUnreserveSlotOrderIDInternalServerError) WithPayload(payload *models.DefaultStatusResponse) *DeleteUnreserveSlotOrderIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete unreserve slot order Id internal server error response
func (o *DeleteUnreserveSlotOrderIDInternalServerError) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUnreserveSlotOrderIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
