// Code generated by go-swagger; DO NOT EDIT.

package delivery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"otusdelivery/internal/models"
)

// GetCheckDeliveryStatusOrderIDOKCode is the HTTP code returned for type GetCheckDeliveryStatusOrderIDOK
const GetCheckDeliveryStatusOrderIDOKCode int = 200

/*
GetCheckDeliveryStatusOrderIDOK Успешное получение данных по балансу

swagger:response getCheckDeliveryStatusOrderIdOK
*/
type GetCheckDeliveryStatusOrderIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.DeliveryStatus `json:"body,omitempty"`
}

// NewGetCheckDeliveryStatusOrderIDOK creates GetCheckDeliveryStatusOrderIDOK with default headers values
func NewGetCheckDeliveryStatusOrderIDOK() *GetCheckDeliveryStatusOrderIDOK {

	return &GetCheckDeliveryStatusOrderIDOK{}
}

// WithPayload adds the payload to the get check delivery status order Id o k response
func (o *GetCheckDeliveryStatusOrderIDOK) WithPayload(payload *models.DeliveryStatus) *GetCheckDeliveryStatusOrderIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get check delivery status order Id o k response
func (o *GetCheckDeliveryStatusOrderIDOK) SetPayload(payload *models.DeliveryStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCheckDeliveryStatusOrderIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCheckDeliveryStatusOrderIDBadRequestCode is the HTTP code returned for type GetCheckDeliveryStatusOrderIDBadRequest
const GetCheckDeliveryStatusOrderIDBadRequestCode int = 400

/*
GetCheckDeliveryStatusOrderIDBadRequest Клиентская ошибка

swagger:response getCheckDeliveryStatusOrderIdBadRequest
*/
type GetCheckDeliveryStatusOrderIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCheckDeliveryStatusOrderIDBadRequest creates GetCheckDeliveryStatusOrderIDBadRequest with default headers values
func NewGetCheckDeliveryStatusOrderIDBadRequest() *GetCheckDeliveryStatusOrderIDBadRequest {

	return &GetCheckDeliveryStatusOrderIDBadRequest{}
}

// WithPayload adds the payload to the get check delivery status order Id bad request response
func (o *GetCheckDeliveryStatusOrderIDBadRequest) WithPayload(payload *models.Error) *GetCheckDeliveryStatusOrderIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get check delivery status order Id bad request response
func (o *GetCheckDeliveryStatusOrderIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCheckDeliveryStatusOrderIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCheckDeliveryStatusOrderIDInternalServerErrorCode is the HTTP code returned for type GetCheckDeliveryStatusOrderIDInternalServerError
const GetCheckDeliveryStatusOrderIDInternalServerErrorCode int = 500

/*
GetCheckDeliveryStatusOrderIDInternalServerError Серверная ошибка

swagger:response getCheckDeliveryStatusOrderIdInternalServerError
*/
type GetCheckDeliveryStatusOrderIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCheckDeliveryStatusOrderIDInternalServerError creates GetCheckDeliveryStatusOrderIDInternalServerError with default headers values
func NewGetCheckDeliveryStatusOrderIDInternalServerError() *GetCheckDeliveryStatusOrderIDInternalServerError {

	return &GetCheckDeliveryStatusOrderIDInternalServerError{}
}

// WithPayload adds the payload to the get check delivery status order Id internal server error response
func (o *GetCheckDeliveryStatusOrderIDInternalServerError) WithPayload(payload *models.Error) *GetCheckDeliveryStatusOrderIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get check delivery status order Id internal server error response
func (o *GetCheckDeliveryStatusOrderIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCheckDeliveryStatusOrderIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
