// Code generated by go-swagger; DO NOT EDIT.

package delivery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCheckDeliveryStatusOrderIDHandlerFunc turns a function with the right signature into a get check delivery status order ID handler
type GetCheckDeliveryStatusOrderIDHandlerFunc func(GetCheckDeliveryStatusOrderIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCheckDeliveryStatusOrderIDHandlerFunc) Handle(params GetCheckDeliveryStatusOrderIDParams) middleware.Responder {
	return fn(params)
}

// GetCheckDeliveryStatusOrderIDHandler interface for that can handle valid get check delivery status order ID params
type GetCheckDeliveryStatusOrderIDHandler interface {
	Handle(GetCheckDeliveryStatusOrderIDParams) middleware.Responder
}

// NewGetCheckDeliveryStatusOrderID creates a new http.Handler for the get check delivery status order ID operation
func NewGetCheckDeliveryStatusOrderID(ctx *middleware.Context, handler GetCheckDeliveryStatusOrderIDHandler) *GetCheckDeliveryStatusOrderID {
	return &GetCheckDeliveryStatusOrderID{Context: ctx, Handler: handler}
}

/*
	GetCheckDeliveryStatusOrderID swagger:route GET /check-delivery-status/{order-id} Delivery getCheckDeliveryStatusOrderId

Получение статуса доставки по заказу
*/
type GetCheckDeliveryStatusOrderID struct {
	Context *middleware.Context
	Handler GetCheckDeliveryStatusOrderIDHandler
}

func (o *GetCheckDeliveryStatusOrderID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCheckDeliveryStatusOrderIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
